/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

%{C++
#ifdef ERROR
#undef ERROR
#endif
%}

[scriptable, uuid(b076e53e-2cb7-40f9-9b9e-b2d3eee5e050)]
interface nsIODBCStorageError : nsISupports {

  /**
   * General SQL error or missing database.
   */
  const long ERROR = 1;


  /**
   * Indicates what type of error occurred.
   */
  readonly attribute long code;

  /**
   * An error string the gives more details, if available.
   */
  readonly attribute AString message;

  readonly attribute AString state;
};
